/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Merriweather } from "next/font/google";

import "./globals.css";

const font1 = Merriweather({
  weight: ["400", "700"], // 필요한 두께 선택
  subsets: ["latin"], // 사용할 문자셋
  variable: "--font-merriweather", // Tailwind에서 사용 가능하도록 변수 선언
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
